# Generated by Django 4.1.3 on 2022-12-13 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profesional_prestacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesional",
            name="comuna",
            field=models.ForeignKey(
                blank=True,
                db_column="id_comuna",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.comuna",
            ),
        ),
        migrations.AlterField(
            model_name="profesional",
            name="region",
            field=models.ForeignKey(
                blank=True,
                db_column="id_region",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.region",
            ),
        ),
    ]
